version: "3.2"

services:
  laravel:
    build: ../
    entrypoint: ""
    env_file: ../.env
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
     - 80:80
  terraform:
    image: hashicorp/terraform:0.12.21
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}